import { DataPribadiType } from '../type/DataUtamaType'

export const listDataPribadi: DataPribadiType[] = [
  {
    id: '1',
    nip: '1234567890',
    nama: 'John Doe',
    jk: 'L',
    tempat_lahir: 'Jakarta',
    tanggal_lahir: '1990-01-01',
    agama: 'Islam',
    alamat: 'Jl. Merdeka No. 1',
    kelurahan: 'Kelurahan A',
    kecamatan: 'Kecamatan B',
    kota: 'Jakarta',
    provinsi: 'DKI Jakarta',
    pos: '12345',
    no_telp: '08123456789',
    email: 'john.doe@example.com',
    separate: false,
  },
  {
    id: '2',
    nip: '0987654321',
    nama: 'Jane Doe',
    jk: 'P',
    tempat_lahir: 'Bandung',
    tanggal_lahir: '1991-02-02',
    agama: 'Kristen',
    alamat: 'Jl. Sudirman No. 2',
    kelurahan: 'Kelurahan C',
    kecamatan: 'Kecamatan D',
    kota: 'Bandung',
    provinsi: 'Jawa Barat',
    pos: '54321',
    no_telp: '08987654321',
    email: 'jane.doe@example.com',
    separate: false,
  },
]
