export const ListDataTableReferensi = [
  'Agama',
  'Instansi',
  'Jenis Jabatan',
  'Pendidikan',
  'Alasan Hukum Disiplin',
  'Jabatan Fungsional',
  'Kanreg',
  'Ref. Jenjang JF',
  'ASN Jenjang Jabatan',
  'Jabatan Fungsional Umum',
  'Kedudukan Hukum',
  'Satuan Kerja',
  'Eselon',
  'Jenis Diklat',
  'Latihan Struktural',
  'Tingkat Pendidikan',
  'Golongan',
  'Jenis Hukuman',
  'Lokasi',
]
