export * from './TableDataPribadi'
export * from './TableDataGolongan'
export * from './TableDataPendidikan'
export * from './TableDataJabatan'
export * from './TableDataDiklat'
export * from './TableDataDiklatLainnya'
export * from './TableDataPenghargaan'
